-- COUNT THE TOTAL NUMBER OF ROWS/TRACKS IN THE SPOTIFY TABLE
SELECT COUNT(*) FROM spotify;

-- COUNT THE NUMBER OF UNIQUE ALBUMS IN THE DATASET
SELECT COUNT(DISTINCT album) FROM spotify;

-- COUNT THE NUMBER OF UNIQUE ARTISTS IN THE DATASET
SELECT COUNT(DISTINCT artist) FROM spotify;

-- LIST ALL UNIQUE TYPES OF ALBUMS (E.G., ALBUM, SINGLE, COMPILATION)
SELECT DISTINCT album_type FROM spotify;

-- FIND THE LONGEST TRACK DURATION IN MINUTES
SELECT MAX(duration_min) FROM spotify;

-- FIND THE SHORTEST TRACK DURATION IN MINUTES
SELECT MIN(duration_min) FROM spotify;

-- LIST ALL UNIQUE CHANNELS ASSOCIATED WITH THE TRACKS
SELECT DISTINCT channel FROM spotify;

-- LIST ALL UNIQUE PLATFORMS WHERE THE SONGS ARE MOST PLAYED
SELECT DISTINCT most_played_on FROM spotify;